language: php
sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - chmod +x bin/install-wp-tests.sh

cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=trunk

script:
  - bash bin/prepare.sh
  - bash bin/test.sh
